apiVersion: skaffold/v2beta19
kind: Config
build:
  local: {}
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
  - context: src
    image: gcr.io/jk-mlops-dev/locust-load-generator 
    sync:
      infer:
      - '**/*.py'
      - '**/*.go'
# defines the Kubernetes manifests to deploy on each run
deploy:
   kustomize:
      paths:
      - manifests
# use the cloudbuild profile to build images using Google Cloud Build
#profiles:
#- name: cloudbuild
#  build:
#    googleCloudBuild: {}