# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: helloworld-multislice 
spec:
  replicatedJobs:
  - name: slice
    replicas: 2
    template:
      spec:
        template:
          spec:
            containers:
            - name: tpu-job 
              command:
              - python3 
              - pedagogical_examples/shardings.py
              - --dcn_data_parallelism=2
              - --ici_fsdp_parallelism=16
              - --batch_size=131072
              - --embedding_dimension=2048

 

