# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metrics.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmetrics.proto\"\x81\x04\n\x07Metrics\x12\x0f\n\x07test_id\x18\x01 \x01(\t\x12\x14\n\x0crequest_type\x18\x02 \x01(\t\x12\x14\n\x0crequest_name\x18\x03 \x01(\t\x12\x17\n\x0fresponse_length\x18\x04 \x01(\x05\x12\x15\n\rresponse_time\x18\x05 \x01(\x02\x12\x12\n\nstart_time\x18\x06 \x01(\t\x12\x11\n\texception\x18\x07 \x01(\t\x12\x14\n\x07request\x18\x08 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08response\x18\t \x01(\tH\x01\x88\x01\x01\x12\x17\n\nmodel_name\x18\n \x01(\tH\x02\x88\x01\x01\x12\x19\n\x0cmodel_method\x18\x0b \x01(\tH\x03\x88\x01\x01\x12\x16\n\ttokenizer\x18\x0c \x01(\tH\x04\x88\x01\x01\x12\x1e\n\x11num_output_tokens\x18\r \x01(\x05H\x05\x88\x01\x01\x12\x1d\n\x10num_input_tokens\x18\x0e \x01(\x05H\x06\x88\x01\x01\x12 \n\x13model_response_time\x18\x0f \x01(\x05H\x07\x88\x01\x01\x42\n\n\x08_requestB\x0b\n\t_responseB\r\n\x0b_model_nameB\x0f\n\r_model_methodB\x0c\n\n_tokenizerB\x14\n\x12_num_output_tokensB\x13\n\x11_num_input_tokensB\x16\n\x14_model_response_timeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metrics_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_METRICS']._serialized_start=18
  _globals['_METRICS']._serialized_end=531
# @@protoc_insertion_point(module_scope)
